<x-layouts.portal :title="'Incident '.$incident->uuid" heading="Incident Operations" :subheading="$incident->uuid" portalRole="admin">
@php($key = fn () => (string) Illuminate\Support\Str::uuid())
<div class="space-y-6">
    @if(session('success'))<div class="rounded-2xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
    <div class="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-sm text-amber-900"><strong>TECHNICAL SEVERITY IS NOT LEGAL MATERIALITY.</strong> All scope is “potentially affected.” Never enter passwords, tokens, full records, or raw evidence.</div>
    <section class="rounded-3xl border bg-white p-6 shadow text-sm"><div class="grid gap-2 md:grid-cols-3"><div><b>Status:</b> {{ $incident->status }}</div><div><b>Severity:</b> {{ $incident->technical_severity }}</div><div><b>Classification:</b> {{ $incident->classification_code }}</div><div><b>Owner:</b> #{{ $incident->owner_user_id }}</div><div><b>Escalation:</b> {{ $incident->escalation_status }}</div><div><b>Detected:</b> {{ $incident->detected_at }}</div></div><p class="mt-4 rounded-xl bg-gray-50 p-3">{{ $incident->technical_summary }}</p></section>

    @if($permissions['privacy.incidents.manage'])
    <section class="rounded-3xl border bg-white p-6 shadow"><h2 class="font-semibold">Technical operations</h2><div class="mt-3 grid gap-4 md:grid-cols-2">
        <form method="POST" action="{{ route('admin.incidents.assign',$incident) }}" class="flex gap-2">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><select name="owner_user_id" class="rounded-xl border-gray-300">@foreach($owners as $o)<option value="{{ $o->id }}">Admin #{{ $o->id }}</option>@endforeach</select><x-likeslocale.button type="submit" variant="secondary">Assign</x-likeslocale.button></form>
        <form method="POST" action="{{ route('admin.incidents.severity',$incident) }}" class="flex gap-2">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><select name="technical_severity" class="rounded-xl border-gray-300">@foreach($taxonomy::SEVERITIES as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><x-likeslocale.button type="submit" variant="secondary">Set severity</x-likeslocale.button></form>
        <form method="POST" action="{{ route('admin.incidents.transition',$incident) }}" class="grid gap-2 md:col-span-2 md:grid-cols-4">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><select name="status" class="rounded-xl border-gray-300">@foreach($taxonomy::STATUSES as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><select name="action_code" class="rounded-xl border-gray-300">@foreach($taxonomy::ACTION_CODES as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><select name="action_result" class="rounded-xl border-gray-300">@foreach($taxonomy::ACTION_RESULTS as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><x-likeslocale.button type="submit" variant="warning">Record transition</x-likeslocale.button></form>
        <form method="POST" action="{{ route('admin.incidents.scope',$incident) }}" class="grid gap-2 md:col-span-2">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><div class="flex flex-wrap gap-2">@foreach($taxonomy::SYSTEMS as $v)<label class="text-xs"><input type="checkbox" name="system_codes[]" value="{{ $v }}"> {{ $v }}</label>@endforeach</div><div class="flex flex-wrap gap-2">@foreach($categories as $v)<label class="text-xs"><input type="checkbox" name="data_categories[]" value="{{ $v }}"> {{ $v }}</label>@endforeach</div><input type="number" min="0" name="potentially_affected_subject_count" placeholder="Aggregate count" class="rounded-xl border-gray-300"><x-likeslocale.button type="submit" variant="secondary">Append scope snapshot</x-likeslocale.button></form>
    </div></section>@endif

    <section class="rounded-3xl border bg-white p-6 shadow"><h2 class="font-semibold">Controller boundary</h2><p class="text-sm text-gray-600">Processor escalation, explicit acknowledgement, and controller-provided decisions are separate evidence.</p><div class="mt-3 flex flex-wrap gap-3">
        @if($permissions['privacy.incidents.escalate'] && $incident->escalation_status==='not_escalated')<form method="POST" action="{{ route('admin.incidents.escalate',$incident) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><x-likeslocale.button type="submit" variant="warning">Record processor escalation</x-likeslocale.button></form>@endif
        @if($permissions['privacy.incidents.controller-decision'] && $incident->escalation_status==='escalated')<form method="POST" action="{{ route('admin.incidents.acknowledge',$incident) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><x-likeslocale.button type="submit" variant="warning">Explicitly acknowledge</x-likeslocale.button></form>@endif
    </div>
    @if($permissions['privacy.incidents.controller-decision'])<form method="POST" action="{{ route('admin.incidents.decision',$incident) }}" class="mt-4 grid gap-2 md:grid-cols-4">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><select name="breach_assessment" class="rounded-xl border-gray-300">@foreach($taxonomy::BREACH_ASSESSMENTS as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><select name="authority_notification_decision" class="rounded-xl border-gray-300">@foreach($taxonomy::NOTIFICATION_DECISIONS as $v)<option value="{{ $v }}">authority: {{ $v }}</option>@endforeach</select><select name="subject_notification_decision" class="rounded-xl border-gray-300">@foreach($taxonomy::NOTIFICATION_DECISIONS as $v)<option value="{{ $v }}">subjects: {{ $v }}</option>@endforeach</select><select name="reason_code" class="rounded-xl border-gray-300">@foreach($taxonomy::DECISION_REASONS as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><textarea maxlength="500" name="rationale" placeholder="Optional minimized rationale; no secrets/PII" class="rounded-xl border-gray-300 md:col-span-3"></textarea><x-likeslocale.button type="submit" variant="warning">Append controller decision</x-likeslocale.button></form>@endif
    <div class="mt-4 space-y-2 text-sm">@forelse($incident->decisions->sortByDesc('version') as $d)<div class="rounded-xl border p-3">v{{ $d->version }} · {{ $d->breach_assessment }} · authority {{ $d->authority_notification_decision }} · subjects {{ $d->subject_notification_decision }} · {{ $d->reason_code }} · {{ $d->decided_at }}</div>@empty<p>No controller decision evidence recorded.</p>@endforelse</div></section>

    @if($permissions['privacy.incidents.manage'] && $canHolds)<section class="rounded-3xl border bg-white p-6 shadow"><h2 class="font-semibold">Explicit evidence preservation</h2><p class="text-sm text-gray-600">Issues a hold through the existing Pass 3 service. Closure/reopen never releases or duplicates it.</p><form method="POST" action="{{ route('admin.incidents.hold',$incident) }}" class="mt-3 grid gap-2 md:grid-cols-3">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><input name="subject_user_id" type="number" min="1" required placeholder="Subject user ID" class="rounded-xl border-gray-300"><select name="scope_type" class="rounded-xl border-gray-300">@foreach(App\Models\LegalHold::SCOPES as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><select name="data_category" class="rounded-xl border-gray-300"><option value="">None</option>@foreach($categories as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><input name="resource_id" type="number" min="1" placeholder="Resource ID if applicable" class="rounded-xl border-gray-300"><select name="hold_code" class="rounded-xl border-gray-300">@foreach(App\Models\LegalHold::HOLD_CODES as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><input name="effective_at" type="datetime-local" required class="rounded-xl border-gray-300"><x-likeslocale.button type="submit" variant="warning">Issue legal hold</x-likeslocale.button></form></section>@endif

    <section class="rounded-3xl border bg-white p-6 shadow"><h2 class="font-semibold">Closure controls</h2><div class="mt-3 flex gap-3">@if($permissions['privacy.incidents.close'] && $incident->status==='resolved')<form method="POST" action="{{ route('admin.incidents.close',$incident) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><x-likeslocale.button type="submit" variant="danger">Close technically</x-likeslocale.button></form>@endif @if($permissions['privacy.incidents.reopen'] && $incident->status==='closed')<form method="POST" action="{{ route('admin.incidents.reopen',$incident) }}" class="flex gap-2">@csrf<input type="hidden" name="idempotency_key" value="{{ $key() }}"><select name="reason_code" class="rounded-xl border-gray-300">@foreach($taxonomy::REOPEN_REASONS as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><x-likeslocale.button type="submit" variant="warning">Reopen</x-likeslocale.button></form>@endif</div></section>

    <section class="rounded-3xl border bg-white p-6 shadow"><h2 class="font-semibold">Append-only operational timeline</h2><div class="mt-3 space-y-2 text-sm">@foreach($incident->events as $event)<div class="rounded-xl border p-3">#{{ $event->sequence }} · {{ $event->event_type }} · admin #{{ $event->actor_user_id }} · {{ $event->occurred_at }} @if($event->safe_metadata)· {{ collect($event->safe_metadata)->map(fn($v,$k)=>$k.'='.($v===true?'yes':($v===false?'no':$v)))->implode(' · ') }}@endif</div>@endforeach</div></section>
</div>
</x-layouts.portal>
